C = gcc

LDLIBS = -lglut -lGL -lGLU -lXmu -lX11  -lm
INC_PATH = /usr/local/include
LIB_PATH = /usr/local/lib

all: mesh_processing

mesh_processing: MainGL.c Geometry.h Geometry.c TriangleMesh.h TriangleMesh.c
	$(C) -O3 -I$(INC_PATH) -o mesh_processing MainGL.c Geometry.c TriangleMesh.c -L$(LIB_PATH) $(LDLIBS)

clean:
	rm mesh_processing

